client_config_backend: file
client_config:
    client_id: 780568565852-ap4598tdqfdmkoapjdt8uh3pi043acb6.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive